default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  database: proyectual_development
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: proyectual_production
  pool: 5
  username: root
  password: <%= ENV["PROYECTUAL_DATABASE_PASSWORD"] %>
  socket: /var/run/mysqld/mysqld.sock
  port: 3306

test:
  default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  database: proyectual_test
  username: root
  password: 
  socket: /tmp/mysql.sock